### ISSUE TITLE
[Enhancement] No CI system / local output option

### ISSUE THREAD

**Issue by HenrikStanley** [karlderkaefer/cdk-notifier#46]
From any CI/CD tool, it is possible to push to a Pull Request from the Github CLI.
For example from inside GitHub actions, anything we would like to post that has been output as a file from another task could be output like this:

```
    - name: Comment on Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr comment --body-file ${{ steps.diff.outputs.comment_file }}
```

My suggestion is to add a NO CI option that does not attempt to post the output, but simple supplies the output file with the markdown in it.

Other systems can then easily just take that output and post it themselves by handing it over without having to worry about specific CI system details.

This would make the tool more versatile and allow for support of other systems without implementing a ton of API details.
